/**
 * Catálogo territorial Guatemala — 22 departamentos y 340 municipios.
 * Derivado de MINFIN TopoJSON (objects.municipios_gtm / departamentos_gtm), Censo 2018.
 * Códigos de departamento "01"–"22" y municipio 4 dígitos (p. ej. "0101" = ciudad Guatemala).
 */
export type DeptoSeed = { codigo: string; nombre: string };
export type MunicipioSeed = { deptoCodigo: string; codigo: string; nombre: string };

export const GUATEMALA_DEPARTAMENTOS: DeptoSeed[] = [
  { codigo: "01", nombre: "Guatemala" },
  { codigo: "02", nombre: "El Progreso" },
  { codigo: "03", nombre: "Sacatepéquez" },
  { codigo: "04", nombre: "Chimaltenango" },
  { codigo: "05", nombre: "Escuintla" },
  { codigo: "06", nombre: "Santa Rosa" },
  { codigo: "07", nombre: "Sololá" },
  { codigo: "08", nombre: "Totonicapán" },
  { codigo: "09", nombre: "Quetzaltenango" },
  { codigo: "10", nombre: "Suchitepéquez" },
  { codigo: "11", nombre: "Retalhuleu" },
  { codigo: "12", nombre: "San Marcos" },
  { codigo: "13", nombre: "Huehuetenango" },
  { codigo: "14", nombre: "Quiché" },
  { codigo: "15", nombre: "Baja Verapaz" },
  { codigo: "16", nombre: "Alta Verapaz" },
  { codigo: "17", nombre: "Petén" },
  { codigo: "18", nombre: "Izabal" },
  { codigo: "19", nombre: "Zacapa" },
  { codigo: "20", nombre: "Chiquimula" },
  { codigo: "21", nombre: "Jalapa" },
  { codigo: "22", nombre: "Jutiapa" }
];

export const GUATEMALA_MUNICIPIOS: MunicipioSeed[] = [
  { deptoCodigo: "01", codigo: "0101", nombre: "Guatemala" },
  { deptoCodigo: "01", codigo: "0102", nombre: "Santa Catarina Pinula" },
  { deptoCodigo: "01", codigo: "0103", nombre: "San José Pinula" },
  { deptoCodigo: "01", codigo: "0104", nombre: "San José Del Golfo" },
  { deptoCodigo: "01", codigo: "0105", nombre: "Palencia" },
  { deptoCodigo: "01", codigo: "0106", nombre: "Chinautla" },
  { deptoCodigo: "01", codigo: "0107", nombre: "San Pedro Ayampuc" },
  { deptoCodigo: "01", codigo: "0108", nombre: "Mixco" },
  { deptoCodigo: "01", codigo: "0109", nombre: "San Pedro Sacatepéquez" },
  { deptoCodigo: "01", codigo: "0110", nombre: "San Juan Sacatepéquez" },
  { deptoCodigo: "01", codigo: "0111", nombre: "San Raymundo" },
  { deptoCodigo: "01", codigo: "0112", nombre: "Chuarrancho" },
  { deptoCodigo: "01", codigo: "0113", nombre: "Fraijanes" },
  { deptoCodigo: "01", codigo: "0114", nombre: "Amatitlán" },
  { deptoCodigo: "01", codigo: "0115", nombre: "Villa Nueva" },
  { deptoCodigo: "01", codigo: "0116", nombre: "Villa Canales" },
  { deptoCodigo: "01", codigo: "0117", nombre: "Petapa" },
  { deptoCodigo: "02", codigo: "0201", nombre: "Guastatoya" },
  { deptoCodigo: "02", codigo: "0202", nombre: "Morazán" },
  { deptoCodigo: "02", codigo: "0203", nombre: "San Agustín Acasaguastlán" },
  { deptoCodigo: "02", codigo: "0204", nombre: "San Cristóbal Acasaguastlán" },
  { deptoCodigo: "02", codigo: "0205", nombre: "El Jícaro" },
  { deptoCodigo: "02", codigo: "0206", nombre: "Sansare" },
  { deptoCodigo: "02", codigo: "0207", nombre: "Sanarate" },
  { deptoCodigo: "02", codigo: "0208", nombre: "San Antonio La Paz" },
  { deptoCodigo: "03", codigo: "0301", nombre: "Antigua Guatemala" },
  { deptoCodigo: "03", codigo: "0302", nombre: "Jocotenango" },
  { deptoCodigo: "03", codigo: "0303", nombre: "Pastores" },
  { deptoCodigo: "03", codigo: "0304", nombre: "Sumpango" },
  { deptoCodigo: "03", codigo: "0305", nombre: "Santo Domingo Xenacoj" },
  { deptoCodigo: "03", codigo: "0306", nombre: "Santiago Sacatepéquez" },
  { deptoCodigo: "03", codigo: "0307", nombre: "San Bartolomé Milpas Altas" },
  { deptoCodigo: "03", codigo: "0308", nombre: "San Lucas Sacatepéquez" },
  { deptoCodigo: "03", codigo: "0309", nombre: "Santa Lucía Milpas Altas" },
  { deptoCodigo: "03", codigo: "0310", nombre: "Magdalena Milpas Altas" },
  { deptoCodigo: "03", codigo: "0311", nombre: "Santa María De Jesús" },
  { deptoCodigo: "03", codigo: "0312", nombre: "Ciudad Vieja" },
  { deptoCodigo: "03", codigo: "0313", nombre: "San Miguel Dueñas" },
  { deptoCodigo: "03", codigo: "0314", nombre: "Alotenango" },
  { deptoCodigo: "03", codigo: "0315", nombre: "San Antonio Aguas Calientes" },
  { deptoCodigo: "03", codigo: "0316", nombre: "Santa Catarina Barahona" },
  { deptoCodigo: "04", codigo: "0401", nombre: "Chimaltenango" },
  { deptoCodigo: "04", codigo: "0402", nombre: "San José Poaquil" },
  { deptoCodigo: "04", codigo: "0403", nombre: "San Martín Jilotepeque" },
  { deptoCodigo: "04", codigo: "0404", nombre: "Comalapa" },
  { deptoCodigo: "04", codigo: "0405", nombre: "Santa Apolonia" },
  { deptoCodigo: "04", codigo: "0406", nombre: "Tecpán Guatemala" },
  { deptoCodigo: "04", codigo: "0407", nombre: "Patzún" },
  { deptoCodigo: "04", codigo: "0408", nombre: "Pochuta" },
  { deptoCodigo: "04", codigo: "0409", nombre: "Patzicía" },
  { deptoCodigo: "04", codigo: "0410", nombre: "Santa Cruz Balanyá" },
  { deptoCodigo: "04", codigo: "0411", nombre: "Acatenango" },
  { deptoCodigo: "04", codigo: "0412", nombre: "Yepocapa" },
  { deptoCodigo: "04", codigo: "0413", nombre: "San Andrés Itzapa" },
  { deptoCodigo: "04", codigo: "0414", nombre: "Parramos" },
  { deptoCodigo: "04", codigo: "0415", nombre: "Zaragoza" },
  { deptoCodigo: "04", codigo: "0416", nombre: "El Tejar" },
  { deptoCodigo: "05", codigo: "0501", nombre: "Escuintla" },
  { deptoCodigo: "05", codigo: "0502", nombre: "Santa Lucía Cotzumalguapa" },
  { deptoCodigo: "05", codigo: "0503", nombre: "La Democracia" },
  { deptoCodigo: "05", codigo: "0504", nombre: "Siquinalá" },
  { deptoCodigo: "05", codigo: "0505", nombre: "Masagua" },
  { deptoCodigo: "05", codigo: "0506", nombre: "Tiquisate" },
  { deptoCodigo: "05", codigo: "0507", nombre: "La Gomera" },
  { deptoCodigo: "05", codigo: "0508", nombre: "Guanagazapa" },
  { deptoCodigo: "05", codigo: "0509", nombre: "San José" },
  { deptoCodigo: "05", codigo: "0510", nombre: "Iztapa" },
  { deptoCodigo: "05", codigo: "0511", nombre: "Palín" },
  { deptoCodigo: "05", codigo: "0512", nombre: "San Vicente Pacaya" },
  { deptoCodigo: "05", codigo: "0513", nombre: "Nueva Concepción" },
  { deptoCodigo: "05", codigo: "0514", nombre: "Sipacate" },
  { deptoCodigo: "06", codigo: "0601", nombre: "Cuilapa" },
  { deptoCodigo: "06", codigo: "0602", nombre: "Barberena" },
  { deptoCodigo: "06", codigo: "0603", nombre: "Santa Rosa De Lima" },
  { deptoCodigo: "06", codigo: "0604", nombre: "Casillas" },
  { deptoCodigo: "06", codigo: "0605", nombre: "San Rafael Las Flores" },
  { deptoCodigo: "06", codigo: "0606", nombre: "Oratorio" },
  { deptoCodigo: "06", codigo: "0607", nombre: "San Juan Tecuaco" },
  { deptoCodigo: "06", codigo: "0608", nombre: "Chiquimulilla" },
  { deptoCodigo: "06", codigo: "0609", nombre: "Taxisco" },
  { deptoCodigo: "06", codigo: "0610", nombre: "Santa María Ixhuatán" },
  { deptoCodigo: "06", codigo: "0611", nombre: "Guazacapán" },
  { deptoCodigo: "06", codigo: "0612", nombre: "Santa Cruz Naranjo" },
  { deptoCodigo: "06", codigo: "0613", nombre: "Pueblo Nuevo Viñas" },
  { deptoCodigo: "06", codigo: "0614", nombre: "Nueva Santa Rosa" },
  { deptoCodigo: "07", codigo: "0701", nombre: "Sololá" },
  { deptoCodigo: "07", codigo: "0702", nombre: "San José Chacayá" },
  { deptoCodigo: "07", codigo: "0703", nombre: "Santa María Visitación" },
  { deptoCodigo: "07", codigo: "0704", nombre: "Santa Lucía Utatlán" },
  { deptoCodigo: "07", codigo: "0705", nombre: "Nahualá" },
  { deptoCodigo: "07", codigo: "0706", nombre: "Santa Catarina Ixtahuacán" },
  { deptoCodigo: "07", codigo: "0707", nombre: "Santa Clara La Laguna" },
  { deptoCodigo: "07", codigo: "0708", nombre: "Concepción" },
  { deptoCodigo: "07", codigo: "0709", nombre: "San Andrés Semetabaj" },
  { deptoCodigo: "07", codigo: "0710", nombre: "Panajachel" },
  { deptoCodigo: "07", codigo: "0711", nombre: "Santa Catarina Palopó" },
  { deptoCodigo: "07", codigo: "0712", nombre: "San Antonio Palopó" },
  { deptoCodigo: "07", codigo: "0713", nombre: "San Lucas Tolimán" },
  { deptoCodigo: "07", codigo: "0714", nombre: "Santa Cruz La Laguna" },
  { deptoCodigo: "07", codigo: "0715", nombre: "San Pablo La Laguna" },
  { deptoCodigo: "07", codigo: "0716", nombre: "San Marcos La Laguna" },
  { deptoCodigo: "07", codigo: "0717", nombre: "San Juan La Laguna" },
  { deptoCodigo: "07", codigo: "0718", nombre: "San Pedro La Laguna" },
  { deptoCodigo: "07", codigo: "0719", nombre: "Santiago Atitlán" },
  { deptoCodigo: "08", codigo: "0801", nombre: "Totonicapán" },
  { deptoCodigo: "08", codigo: "0802", nombre: "San Cristóbal Totonicapán" },
  { deptoCodigo: "08", codigo: "0803", nombre: "San Francisco El Alto" },
  { deptoCodigo: "08", codigo: "0804", nombre: "San Andrés Xecul" },
  { deptoCodigo: "08", codigo: "0805", nombre: "Momostenango" },
  { deptoCodigo: "08", codigo: "0806", nombre: "Santa María Chiquimula" },
  { deptoCodigo: "08", codigo: "0807", nombre: "Santa Lucía La Reforma" },
  { deptoCodigo: "08", codigo: "0808", nombre: "San Bartolo Aguas Calientes" },
  { deptoCodigo: "09", codigo: "0901", nombre: "Quetzaltenango" },
  { deptoCodigo: "09", codigo: "0902", nombre: "Salcajá" },
  { deptoCodigo: "09", codigo: "0903", nombre: "Olintepeque" },
  { deptoCodigo: "09", codigo: "0904", nombre: "San Carlos Sija" },
  { deptoCodigo: "09", codigo: "0905", nombre: "Sibilia" },
  { deptoCodigo: "09", codigo: "0906", nombre: "Cabricán" },
  { deptoCodigo: "09", codigo: "0907", nombre: "Cajolá" },
  { deptoCodigo: "09", codigo: "0908", nombre: "San Miguel Sigüilá" },
  { deptoCodigo: "09", codigo: "0909", nombre: "San Juan Ostuncalco" },
  { deptoCodigo: "09", codigo: "0910", nombre: "San Mateo" },
  { deptoCodigo: "09", codigo: "0911", nombre: "Concepción Chiquirichapa" },
  { deptoCodigo: "09", codigo: "0912", nombre: "San Martín Sacatepéquez" },
  { deptoCodigo: "09", codigo: "0913", nombre: "Almolonga" },
  { deptoCodigo: "09", codigo: "0914", nombre: "Cantel" },
  { deptoCodigo: "09", codigo: "0915", nombre: "Huitán" },
  { deptoCodigo: "09", codigo: "0916", nombre: "Zunil" },
  { deptoCodigo: "09", codigo: "0917", nombre: "Colomba" },
  { deptoCodigo: "09", codigo: "0918", nombre: "San Francisco La Unión" },
  { deptoCodigo: "09", codigo: "0919", nombre: "El Palmar" },
  { deptoCodigo: "09", codigo: "0920", nombre: "Coatepeque" },
  { deptoCodigo: "09", codigo: "0921", nombre: "Génova" },
  { deptoCodigo: "09", codigo: "0922", nombre: "Flores Costa Cuca" },
  { deptoCodigo: "09", codigo: "0923", nombre: "La Esperanza" },
  { deptoCodigo: "09", codigo: "0924", nombre: "Palestina De los Altos" },
  { deptoCodigo: "10", codigo: "1001", nombre: "Mazatenango" },
  { deptoCodigo: "10", codigo: "1002", nombre: "Cuyotenango" },
  { deptoCodigo: "10", codigo: "1003", nombre: "San Francisco Zapotitlán" },
  { deptoCodigo: "10", codigo: "1004", nombre: "San Bernardino" },
  { deptoCodigo: "10", codigo: "1005", nombre: "San José El Ídolo" },
  { deptoCodigo: "10", codigo: "1006", nombre: "Santo Domingo Suchitepéquez" },
  { deptoCodigo: "10", codigo: "1007", nombre: "San Lorenzo" },
  { deptoCodigo: "10", codigo: "1008", nombre: "Samayac" },
  { deptoCodigo: "10", codigo: "1009", nombre: "San Pablo Jocopilas" },
  { deptoCodigo: "10", codigo: "1010", nombre: "San Antonio Suchitepéquez" },
  { deptoCodigo: "10", codigo: "1011", nombre: "San Miguel Panán" },
  { deptoCodigo: "10", codigo: "1012", nombre: "San Gabriel" },
  { deptoCodigo: "10", codigo: "1013", nombre: "Chicacao" },
  { deptoCodigo: "10", codigo: "1014", nombre: "Patulul" },
  { deptoCodigo: "10", codigo: "1015", nombre: "Santa Bárbara" },
  { deptoCodigo: "10", codigo: "1016", nombre: "San Juan Bautista" },
  { deptoCodigo: "10", codigo: "1017", nombre: "Santo Tomás La Unión" },
  { deptoCodigo: "10", codigo: "1018", nombre: "Zunilito" },
  { deptoCodigo: "10", codigo: "1019", nombre: "Pueblo Nuevo" },
  { deptoCodigo: "10", codigo: "1020", nombre: "Río Bravo" },
  { deptoCodigo: "10", codigo: "1021", nombre: "San José La Máquina" },
  { deptoCodigo: "11", codigo: "1101", nombre: "Retalhuleu" },
  { deptoCodigo: "11", codigo: "1102", nombre: "San Sebastián" },
  { deptoCodigo: "11", codigo: "1103", nombre: "Santa Cruz Muluá" },
  { deptoCodigo: "11", codigo: "1104", nombre: "San Martín Zapotitlán" },
  { deptoCodigo: "11", codigo: "1105", nombre: "San Felipe" },
  { deptoCodigo: "11", codigo: "1106", nombre: "San Andrés Villa Seca" },
  { deptoCodigo: "11", codigo: "1107", nombre: "Champerico" },
  { deptoCodigo: "11", codigo: "1108", nombre: "Nuevo San Carlos" },
  { deptoCodigo: "11", codigo: "1109", nombre: "El Asintal" },
  { deptoCodigo: "12", codigo: "1201", nombre: "San Marcos" },
  { deptoCodigo: "12", codigo: "1202", nombre: "San Pedro Sacatepéquez" },
  { deptoCodigo: "12", codigo: "1203", nombre: "San Antonio Sacatepéquez" },
  { deptoCodigo: "12", codigo: "1204", nombre: "Comitancillo" },
  { deptoCodigo: "12", codigo: "1205", nombre: "San Miguel Ixtahuacán" },
  { deptoCodigo: "12", codigo: "1206", nombre: "Concepción Tutuapa" },
  { deptoCodigo: "12", codigo: "1207", nombre: "Tacaná" },
  { deptoCodigo: "12", codigo: "1208", nombre: "Sibinal" },
  { deptoCodigo: "12", codigo: "1209", nombre: "Tajumulco" },
  { deptoCodigo: "12", codigo: "1210", nombre: "Tejutla" },
  { deptoCodigo: "12", codigo: "1211", nombre: "San Rafael Pie De La Cuesta" },
  { deptoCodigo: "12", codigo: "1212", nombre: "Nuevo Progreso" },
  { deptoCodigo: "12", codigo: "1213", nombre: "El Tumbador" },
  { deptoCodigo: "12", codigo: "1214", nombre: "El Rodeo" },
  { deptoCodigo: "12", codigo: "1215", nombre: "Malacatán" },
  { deptoCodigo: "12", codigo: "1216", nombre: "Catarina" },
  { deptoCodigo: "12", codigo: "1217", nombre: "Ayutla" },
  { deptoCodigo: "12", codigo: "1218", nombre: "Ocós" },
  { deptoCodigo: "12", codigo: "1219", nombre: "San Pablo" },
  { deptoCodigo: "12", codigo: "1220", nombre: "El Quetzal" },
  { deptoCodigo: "12", codigo: "1221", nombre: "La Reforma" },
  { deptoCodigo: "12", codigo: "1222", nombre: "Pajapita" },
  { deptoCodigo: "12", codigo: "1223", nombre: "Ixchiguán" },
  { deptoCodigo: "12", codigo: "1224", nombre: "San José Ojetenam" },
  { deptoCodigo: "12", codigo: "1225", nombre: "San Cristóbal Cucho" },
  { deptoCodigo: "12", codigo: "1226", nombre: "Sipacapa" },
  { deptoCodigo: "12", codigo: "1227", nombre: "Esquipulas Palo Gordo" },
  { deptoCodigo: "12", codigo: "1228", nombre: "Río Blanco" },
  { deptoCodigo: "12", codigo: "1229", nombre: "San Lorenzo" },
  { deptoCodigo: "12", codigo: "1230", nombre: "La Blanca" },
  { deptoCodigo: "13", codigo: "1301", nombre: "Huehuetenango" },
  { deptoCodigo: "13", codigo: "1302", nombre: "Chiantla" },
  { deptoCodigo: "13", codigo: "1303", nombre: "Malacatancito" },
  { deptoCodigo: "13", codigo: "1304", nombre: "Cuilco" },
  { deptoCodigo: "13", codigo: "1305", nombre: "Nentón" },
  { deptoCodigo: "13", codigo: "1306", nombre: "San Pedro Necta" },
  { deptoCodigo: "13", codigo: "1307", nombre: "Jacaltenango" },
  { deptoCodigo: "13", codigo: "1308", nombre: "Soloma" },
  { deptoCodigo: "13", codigo: "1309", nombre: "San Ildefonso Ixtahuacán" },
  { deptoCodigo: "13", codigo: "1310", nombre: "Santa Bárbara" },
  { deptoCodigo: "13", codigo: "1311", nombre: "La Libertad" },
  { deptoCodigo: "13", codigo: "1312", nombre: "La Democracia" },
  { deptoCodigo: "13", codigo: "1313", nombre: "San Miguel Acatán" },
  { deptoCodigo: "13", codigo: "1314", nombre: "San Rafael La Independencia" },
  { deptoCodigo: "13", codigo: "1315", nombre: "Todos Santos Cuchumatán" },
  { deptoCodigo: "13", codigo: "1316", nombre: "San Juan Atitán" },
  { deptoCodigo: "13", codigo: "1317", nombre: "Santa Eulalia" },
  { deptoCodigo: "13", codigo: "1318", nombre: "San Mateo Ixtatán" },
  { deptoCodigo: "13", codigo: "1319", nombre: "Colotenango" },
  { deptoCodigo: "13", codigo: "1320", nombre: "San Sebastián Huehuetenango" },
  { deptoCodigo: "13", codigo: "1321", nombre: "Tectitán" },
  { deptoCodigo: "13", codigo: "1322", nombre: "Concepción Huista" },
  { deptoCodigo: "13", codigo: "1323", nombre: "San Juan Ixcoy" },
  { deptoCodigo: "13", codigo: "1324", nombre: "San Antonio Huista" },
  { deptoCodigo: "13", codigo: "1325", nombre: "San Sebastián Coatán" },
  { deptoCodigo: "13", codigo: "1326", nombre: "Barillas" },
  { deptoCodigo: "13", codigo: "1327", nombre: "Aguacatán" },
  { deptoCodigo: "13", codigo: "1328", nombre: "San Rafael Pétzal" },
  { deptoCodigo: "13", codigo: "1329", nombre: "San Gaspar Ixchil" },
  { deptoCodigo: "13", codigo: "1330", nombre: "Santiago Chimaltenango" },
  { deptoCodigo: "13", codigo: "1331", nombre: "Santa Ana Huista" },
  { deptoCodigo: "13", codigo: "1332", nombre: "Unión Cantinil" },
  { deptoCodigo: "13", codigo: "1333", nombre: "Petatán" },
  { deptoCodigo: "14", codigo: "1401", nombre: "Santa Cruz Del Quiché" },
  { deptoCodigo: "14", codigo: "1402", nombre: "Chiché" },
  { deptoCodigo: "14", codigo: "1403", nombre: "Chinique" },
  { deptoCodigo: "14", codigo: "1404", nombre: "Zacualpa" },
  { deptoCodigo: "14", codigo: "1405", nombre: "Chajul" },
  { deptoCodigo: "14", codigo: "1406", nombre: "Chichicastenango" },
  { deptoCodigo: "14", codigo: "1407", nombre: "Patzité" },
  { deptoCodigo: "14", codigo: "1408", nombre: "San Antonio Ilotenango" },
  { deptoCodigo: "14", codigo: "1409", nombre: "San Pedro Jocopilas" },
  { deptoCodigo: "14", codigo: "1410", nombre: "Cunén" },
  { deptoCodigo: "14", codigo: "1411", nombre: "San Juan Cotzal" },
  { deptoCodigo: "14", codigo: "1412", nombre: "Joyabaj" },
  { deptoCodigo: "14", codigo: "1413", nombre: "Nebaj" },
  { deptoCodigo: "14", codigo: "1414", nombre: "San Andrés Sajcabajá" },
  { deptoCodigo: "14", codigo: "1415", nombre: "Uspantán" },
  { deptoCodigo: "14", codigo: "1416", nombre: "Sacapulas" },
  { deptoCodigo: "14", codigo: "1417", nombre: "San Bartolomé Jocotenango" },
  { deptoCodigo: "14", codigo: "1418", nombre: "Canillá" },
  { deptoCodigo: "14", codigo: "1419", nombre: "Chicamán" },
  { deptoCodigo: "14", codigo: "1420", nombre: "Ixcán" },
  { deptoCodigo: "14", codigo: "1421", nombre: "Pachalum" },
  { deptoCodigo: "15", codigo: "1501", nombre: "Salamá" },
  { deptoCodigo: "15", codigo: "1502", nombre: "San Miguel Chicaj" },
  { deptoCodigo: "15", codigo: "1503", nombre: "Rabinal" },
  { deptoCodigo: "15", codigo: "1504", nombre: "Cubulco" },
  { deptoCodigo: "15", codigo: "1505", nombre: "Granados" },
  { deptoCodigo: "15", codigo: "1506", nombre: "El Chol" },
  { deptoCodigo: "15", codigo: "1507", nombre: "San Jerónimo" },
  { deptoCodigo: "15", codigo: "1508", nombre: "Purulhá" },
  { deptoCodigo: "16", codigo: "1601", nombre: "Cobán" },
  { deptoCodigo: "16", codigo: "1602", nombre: "Santa Cruz Verapaz" },
  { deptoCodigo: "16", codigo: "1603", nombre: "San Cristóbal Verapaz" },
  { deptoCodigo: "16", codigo: "1604", nombre: "Tactic" },
  { deptoCodigo: "16", codigo: "1605", nombre: "Tamahú" },
  { deptoCodigo: "16", codigo: "1606", nombre: "Tucurú" },
  { deptoCodigo: "16", codigo: "1607", nombre: "Panzós" },
  { deptoCodigo: "16", codigo: "1608", nombre: "Senahú" },
  { deptoCodigo: "16", codigo: "1609", nombre: "San Pedro Carchá" },
  { deptoCodigo: "16", codigo: "1610", nombre: "San Juan Chamelco" },
  { deptoCodigo: "16", codigo: "1611", nombre: "Lanquín" },
  { deptoCodigo: "16", codigo: "1612", nombre: "Cahabón" },
  { deptoCodigo: "16", codigo: "1613", nombre: "Chisec" },
  { deptoCodigo: "16", codigo: "1614", nombre: "Chahal" },
  { deptoCodigo: "16", codigo: "1615", nombre: "Fray Bartolomé De Las Casas" },
  { deptoCodigo: "16", codigo: "1616", nombre: "Santa Catalina La Tinta" },
  { deptoCodigo: "16", codigo: "1617", nombre: "Raxruhá" },
  { deptoCodigo: "17", codigo: "1701", nombre: "Flores" },
  { deptoCodigo: "17", codigo: "1702", nombre: "San José" },
  { deptoCodigo: "17", codigo: "1703", nombre: "San Benito" },
  { deptoCodigo: "17", codigo: "1704", nombre: "San Andrés" },
  { deptoCodigo: "17", codigo: "1705", nombre: "La Libertad" },
  { deptoCodigo: "17", codigo: "1706", nombre: "San Francisco" },
  { deptoCodigo: "17", codigo: "1707", nombre: "Santa Ana" },
  { deptoCodigo: "17", codigo: "1708", nombre: "Dolores" },
  { deptoCodigo: "17", codigo: "1709", nombre: "San Luis" },
  { deptoCodigo: "17", codigo: "1710", nombre: "Sayaxché" },
  { deptoCodigo: "17", codigo: "1711", nombre: "Melchor De Mencos" },
  { deptoCodigo: "17", codigo: "1712", nombre: "Poptún" },
  { deptoCodigo: "17", codigo: "1713", nombre: "Las Cruces" },
  { deptoCodigo: "17", codigo: "1714", nombre: "El Chal" },
  { deptoCodigo: "18", codigo: "1801", nombre: "Puerto Barrios" },
  { deptoCodigo: "18", codigo: "1802", nombre: "Livingston" },
  { deptoCodigo: "18", codigo: "1803", nombre: "El Estor" },
  { deptoCodigo: "18", codigo: "1804", nombre: "Morales" },
  { deptoCodigo: "18", codigo: "1805", nombre: "Los Amates" },
  { deptoCodigo: "19", codigo: "1901", nombre: "Zacapa" },
  { deptoCodigo: "19", codigo: "1902", nombre: "Estanzuela" },
  { deptoCodigo: "19", codigo: "1903", nombre: "Río Hondo" },
  { deptoCodigo: "19", codigo: "1904", nombre: "Gualán" },
  { deptoCodigo: "19", codigo: "1905", nombre: "Teculután" },
  { deptoCodigo: "19", codigo: "1906", nombre: "Usumatlán" },
  { deptoCodigo: "19", codigo: "1907", nombre: "Cabañas" },
  { deptoCodigo: "19", codigo: "1908", nombre: "San Diego" },
  { deptoCodigo: "19", codigo: "1909", nombre: "La Unión" },
  { deptoCodigo: "19", codigo: "1910", nombre: "Huité" },
  { deptoCodigo: "19", codigo: "1911", nombre: "San Jorge" },
  { deptoCodigo: "20", codigo: "2001", nombre: "Chiquimula" },
  { deptoCodigo: "20", codigo: "2002", nombre: "San José La Arada" },
  { deptoCodigo: "20", codigo: "2003", nombre: "San Juan Ermita" },
  { deptoCodigo: "20", codigo: "2004", nombre: "Jocotán" },
  { deptoCodigo: "20", codigo: "2005", nombre: "Camotán" },
  { deptoCodigo: "20", codigo: "2006", nombre: "Olopa" },
  { deptoCodigo: "20", codigo: "2007", nombre: "Esquipulas" },
  { deptoCodigo: "20", codigo: "2008", nombre: "Concepción Las Minas" },
  { deptoCodigo: "20", codigo: "2009", nombre: "Quezaltepeque" },
  { deptoCodigo: "20", codigo: "2010", nombre: "San Jacinto" },
  { deptoCodigo: "20", codigo: "2011", nombre: "Ipala" },
  { deptoCodigo: "21", codigo: "2101", nombre: "Jalapa" },
  { deptoCodigo: "21", codigo: "2102", nombre: "San Pedro Pinula" },
  { deptoCodigo: "21", codigo: "2103", nombre: "San Luis Jilotepeque" },
  { deptoCodigo: "21", codigo: "2104", nombre: "San Manuel Chaparrón" },
  { deptoCodigo: "21", codigo: "2105", nombre: "San Carlos Alzatate" },
  { deptoCodigo: "21", codigo: "2106", nombre: "Monjas" },
  { deptoCodigo: "21", codigo: "2107", nombre: "Mataquescuintla" },
  { deptoCodigo: "22", codigo: "2201", nombre: "Jutiapa" },
  { deptoCodigo: "22", codigo: "2202", nombre: "El Progreso" },
  { deptoCodigo: "22", codigo: "2203", nombre: "Santa Catarina Mita" },
  { deptoCodigo: "22", codigo: "2204", nombre: "Agua Blanca" },
  { deptoCodigo: "22", codigo: "2205", nombre: "Asunción Mita" },
  { deptoCodigo: "22", codigo: "2206", nombre: "Yupiltepeque" },
  { deptoCodigo: "22", codigo: "2207", nombre: "Atescatempa" },
  { deptoCodigo: "22", codigo: "2208", nombre: "Jerez" },
  { deptoCodigo: "22", codigo: "2209", nombre: "El Adelanto" },
  { deptoCodigo: "22", codigo: "2210", nombre: "Zapotitlán" },
  { deptoCodigo: "22", codigo: "2211", nombre: "Comapa" },
  { deptoCodigo: "22", codigo: "2212", nombre: "Jalpatagua" },
  { deptoCodigo: "22", codigo: "2213", nombre: "Conguaco" },
  { deptoCodigo: "22", codigo: "2214", nombre: "Moyuta" },
  { deptoCodigo: "22", codigo: "2215", nombre: "Pasaco" },
  { deptoCodigo: "22", codigo: "2216", nombre: "San José Acatempa" },
  { deptoCodigo: "22", codigo: "2217", nombre: "Quesada" }
];
